# Generated by Django 2.2.4 on 2023-06-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='password',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='image',
            field=models.CharField(default='hey', max_length=255),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
