# Generated by Django 2.2.4 on 2023-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230617_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='hey', max_length=255),
        ),
    ]
