# Generated by Django 2.2.4 on 2023-06-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_address'),
        ('main_app', '0002_auto_20230617_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='users_who_dislike',
            field=models.ManyToManyField(related_name='disliked_activities', to='login_app.User'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_activities', to='login_app.User'),
        ),
    ]
