# Generated by Django 2.2.4 on 2023-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230617_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
